### ISSUE TITLE
Question about the Arduino side of your code

### ISSUE THREAD

**Issue by ilovetogetspamed** [ellisgl/Brewnoduino#1]
What firmata library are you using on your arduino?  A custom to support 1-Wire?
Thanks

**Comment by rjrodd** [comment]
I've tried the code provided from firmatabuilder.com, with the one-wire feature support selected, but no luck getting any addresses back in response to `board.sendOneWireSearch()` yet.

**Comment by ellisgl** [comment]
Man - I didn't even notice the original question. Since it was 5 years ago (2013) it was what ever was available at the the time. I used the DS18B20 sensor, so I just looked up some stuff for that. 

https://github.com/firmata/protocol/blob/master/onewire.md for more information on the arduino side.

**Comment by ilovetogetspamed** [comment]
Thanks
